version: '3.7'

services:

  url_lookup:
    build:
      context: ./services/url_lookup
      dockerfile: Dockerfile
    volumes:
      - './services/url_lookup:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@url-db:5432/url_dev  
      - DATABASE_TEST_URL=postgres://postgres:postgres@url-db:5432/url_test  
    depends_on:  
      - url-db

  url-db:
    build:
      context: ./services/url_lookup/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres